name: "MVN_RELEASE"

on:
  workflow_dispatch:
  pull_request_target:
    types: [ closed ]
    branches:
      - main
      - master
      - default
    paths:
      #  trigger ALL files (wildcard that matches any file or folder)
      - '**'
      #  trigger not when .yml and .md files that are not located in the .github folder
      - '!/.github/**/*.yml'
      - '!/.github/**/*.md'
  schedule:
    - cron: "0 7 * * *"

jobs:
  java_update:
    name: "java"
    uses: codespacedev/commons/.github/workflows/wc_java_update.yml@main
    secrets:
      G_TOKEN: ${{secrets.CI_TOKEN_WORKFLOW}}
  java_test:
    needs: "java_update"
    name: "java"
    uses: codespacedev/commons/.github/workflows/wc_java_test.yml@main
    secrets:
      G_TOKEN: ${{secrets.CI_TOKEN_WORKFLOW}}
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
